CS-7:crate basic react schedule-calendar
Yaroslaww-1/campus pull request #8
Opened 2021-09-28 20:14 UTC by Sonya-Shultz

for view go to localhost:3000/schedule

2021-09-28 20:35 UTC, Yaroslaww-1 requested changes

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/comp/AllTable.tsx
> +/* eslint-disable react/display-name */
I do not know what this rule used for, but disabling it is not a best idea
Rename folder to components. Also, this file is container as it has connection to state

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/comp/HeaderRow.tsx
> +import "./style/OneTable.scss";
import styles from './styles.module.scss'

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/comp/HeaderRow.tsx
> +    { id:7, name:"Неділя" }];
move it to Event model and create api/services/events service

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/comp/OneCell.tsx
> +export const OneCell: React.FC = () => {
Rename to EventComponent and receive event using props

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/comp/OneRowOfTable.tsx
> +    data: Array<{id:number}>
move it to Event model

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/comp/AllTable.tsx
> +export const AllTable = observer(class extends Component{
Rename to SchedulePage

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/comp/OneTable.tsx
> +export const OneTable: React.FC = () => {
I'd rather do it in this way:
`
export const WeeklyScheduleTableComponent({
events
})
`

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/index.tsx
> +  <Provider {...stores}>
We use `observer` instead of `Provider`. See pages/posts/index.tsx

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/stores/scheduleStore.tsx
> +};
We do not have such a complex data schema. Please use event schema from here https://trello.com/c/XcwIN6Fe/26-cs-19-setup-schedule-loading-backend

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/stores/scheduleStore.tsx
> +export default scheduleStore;
Replace it by real mobx state example. You can use posts.state as an example.

2021-09-28 20:35 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/comp/style/OneTable.scss
> +}
In scss you can nest styles:
```
.root {
  h1 {
  }

  .currentWeek {
  }
}
```

2021-10-05 20:40 UTC, Yaroslaww-1 requested changes

2021-10-05 20:40 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/WeekScheduleTableComponent.tsx
> +        <OneRowOfTable key={item.id} time={item.time} data={weekEvents}/>
I think its better to render by columns, so we can call component `DayScheduleTableComponent`. But rendering by rows is also OK. Though `OneRowOfTable` is a bad naming. Let's call it `OnePairIntervalComponent`

2021-10-05 20:40 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/styles.module.scss
> +.description:hover>.pairDesk, .teacherName:hover>.teacherFullName{
Issue remains the same. Use scss nesting

2021-10-05 20:40 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/schedule.state.ts
> +export const timesState = new TimesState();
I think we can hardcode all intervals and days into constants and do not fetch them from server

2021-10-05 20:40 UTC, Yaroslaww-1 commented on frontend/src/api/services/event.service.ts
> +}
I think we can hardcode all intervals and days into constants and do not fetch them from server

2021-10-05 20:40 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/EventComponent.tsx
> +  const one_events = (event.filter(el => el.time.substr(12, 5) == time ))
1. use `oneEvent` naming (camelCase instead of snake_case)
2. parsing datas like that is a bad practice. We can use https://www.npmjs.com/package/luxon

2021-10-05 20:40 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/EventComponent.tsx
> +    <div className={styles.tmpP}>
what is tmpP?)

2021-10-05 20:40 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/EventComponent.tsx
> +  event: Event[];
I think we do not to handle need multiple events in the same time. You can pass simple `event` as a prop

2021-10-05 20:42 UTC, Yaroslaww-1 requested changes

2021-10-05 20:42 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/ScheduleTables.tsx
> +      <h1>Перший тиждень</h1>
Lets use english everywhere

2021-10-14 17:02 UTC, Yaroslaww-1 requested changes

2021-10-14 17:02 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/EventComponent.tsx
> +  //console.log(event);
Do you need this check?

2021-10-14 17:02 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/OnePairIntervalComponent.tsx
> +  const { DateTime } = require("luxon");
Import {DateTime} from 'luxon'; at the top of the file

2021-10-14 17:02 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/OnePairIntervalComponent.tsx
> +          return pairTime == item;})[0]}
Simplify it please. Maybe move to some functions (you can place functions directly in component)

2021-10-14 17:02 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/WeekScheduleTableComponent.tsx
> +          data={weekEvents.filter(el => DateTime.fromISO(el.time).weekday == parseInt(item.toString()))}
Same as above

2021-10-14 17:02 UTC, Yaroslaww-1 commented on frontend/src/pages/schedule/components/EventComponent.tsx
> +  dayId: number;
DayId?

2021-10-15 12:31 UTC, Sonya-Shultz commented on frontend/src/pages/schedule/components/EventComponent.tsx
> +  //console.log(event);
We need it, because when event is undefined (The pair is missing on schedule) we can't access to fields and it raise errors.

2021-10-21 07:36 UTC, merged